"""Ranking-only identities (#7; app #309).

Sailors who appear in the pre-2009 season rankings but in no imported
series - the events of that era aren't sourced (2004-2008), so these
manifest entries exist purely to anchor their ranking rows and career
arcs. Same golden-record contract as manifest.py: the slug is the key
and the public handle, curate names freely, group/split by editing
entries. Drafted by `ranking.py draft-identities` (grouped by
normalized name across adjacent seasons, sail-corroborated where the
sheets print sails); curation decisions belong here, like manifest.py.
"""
from identity_manifest import C

IDENTITIES = [
    C(slug="alanna-crawford-qeh9", name="Alanna Crawford",
      ranking_rows=["iodai-ranking-2021-senior"], rows=[]),
    C(slug="ana-strappe-qeh9", name="Ana Strappe",
      ranking_rows=["iodai-ranking-2021-senior"], rows=[]),
    C(slug="lisa-whyte-qeh9", name="Lisa Whyte",
      ranking_rows=["iodai-ranking-2021-senior"], rows=[]),
    C(slug="lui-ivory-qeh9", name="Lui Ivory",
      ranking_rows=["iodai-ranking-2021-senior"], rows=[]),
    C(slug="ronan-quinlan-7bcm", name="Ronan Quinlan",
      ranking_rows=["iodai-ranking-2021-junior"], rows=[]),
    C(slug="adam-hill-63jc", name="Adam Hill",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="adam-lawless-rn49", name="Adam Lawless",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="adam-mccullough-afsz", name="Adam McCullough",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="aisling-byrne-ryan-6ap9", name="Aisling Byrne Ryan",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="aisling-judge-eg3u", name="Aisling Judge",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="alan-kingston-s2xb", name="Alan Kingston",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="alan-ruigrok-eg3u", name="Alan Ruigrok",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="alexander-delamer-afsz", name="Alexander Delamer",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="alexandra-morehead-63jc", name="Alexandra Morehead",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="alfred-guy-63jc", name="Alfred Guy",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="ali-dix-n7ek", name="Ali Dix",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="alison-dix-3k4y", name="Alison Dix",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2007"], rows=[]),
    C(slug="alison-kelly-nsju", name="Alison Kelly",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2006"], rows=[]),
    C(slug="allison-green-6ap9", name="Allison Green",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="alvy-burke-eg3u", name="Alvy Burke",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="alyson-rumball-rn49", name="Alyson Rumball",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="amy-buckley-n7ek", name="Amy Buckley",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="amy-kate-trevor-63jc", name="Amy-Kate Trevor",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="andrew-mackey-n7ek", name="Andrew Mackey",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="andrew-ryan-rn49", name="Andrew Ryan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="andrew-tyrell-3k4y", name="Andrew Tyrell",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2007"], rows=[]),
    C(slug="andrew-tyrrell-nsju", name="Andrew Tyrrell",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2006"], rows=[]),
    C(slug="aoife-moriarty-6ap9", name="Aoife Moriarty",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="aoife-o-connell-rn49", name="Aoife O'Connell",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="aoife-o-sullivan-n7ek", name="Aoife O'Sullivan",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="austin-hynes-s2xb", name="Austin Hynes",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="ayden-clarke-6ap9", name="Ayden Clarke",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="barra-collins-rn49", name="Barra Collins",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="barry-fitzgerald-6ap9", name="Barry Fitzgerald",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="ben-scalan-rn49", name="Ben Scalan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="breifne-muldoon-n7ek", name="Breifne Muldoon",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="brendan-costello-t2xb", name="Brendan Costello",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="brian-kelleher-rn49", name="Brian Kelleher",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="brian-vaughan-eg3u", name="Brian Vaughan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="cailean-campbell-n7ek", name="Cailean Campbell",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="caoimhe-salter-rn49", name="Caoimhe Salter",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="catherine-vaughan-rn49", name="Catherine Vaughan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="chloe-crosbie-63jc", name="Chloe Crosbie",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="chris-phelan-afsz", name="Chris Phelan",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="christopher-phelan-n7ek", name="Christopher Phelan",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="cian-cahill-afsz", name="Cian Cahill",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="cian-o-leary-hegarty-afsz", name="Cian O'Leary Hegarty",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="cian-o-regan-fgqk", name="Cian O'Regan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="ciara-browne-eg3u", name="Ciara Browne",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="ciara-fenton-s2xb", name="Ciara Fenton",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="ciara-holahan-afsz", name="Ciara Holahan",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="ciara-holohan-t2xb", name="Ciara Holohan",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="ciara-power-63jc", name="Ciara Power",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="cillian-dickson-eg3u", name="Cillian Dickson",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="cillian-o-connell-eg3u", name="Cillian O'Connell",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="claire-drury-n7ek", name="Claire Drury",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="clare-drury-rn49", name="Clare Drury",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="colm-foy-t2xb", name="Colm Foy",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="connor-cunnigham-n7ek", name="Connor Cunnigham",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="connor-lydon-n7ek", name="Connor Lydon",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="conor-dolan-eg3u", name="Conor Dolan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="conor-fitzgibbon-rn49", name="Conor Fitzgibbon",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="conor-lyden-afsz", name="Conor Lyden",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="conor-mulvin-eg3u", name="Conor Mulvin",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="conor-stallard-rn49", name="Conor Stallard",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="conrad-ryan-6ap9", name="Conrad Ryan",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="cormac-barry-7acu", name="Cormac Barry",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="cormac-dickson-fgqk", name="Cormac Dickson",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="daniel-browne-fgqk", name="Daniel Browne",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="daniel-mccarty-rn49", name="Daniel McCarty",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="darragh-muldoon-afsz", name="Darragh Muldoon",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="darragh-o-shea-afsz", name="Darragh O'Shea",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="david-gray-rn49", name="David Gray",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="david-kavanagh-afsz", name="David Kavanagh",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="david-kenefick-eg3u", name="David Kenefick",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="david-mccormick-rn49", name="David McCormick",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="david-mcgwynne-7acu", name="David McGwynne",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="david-potterton-afsz", name="David Potterton",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="david-whitaker-afsz", name="David Whitaker",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="dermot-o-flynn-s2xb", name="Dermot O'Flynn",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="desmond-fitzgerald-rn49", name="Desmond Fitzgerald",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="diana-kissane-fgqk", name="Diana Kissane",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="donagh-good-rn49", name="Donagh Good",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="ed-butler-rn49", name="Ed Butler",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="eimear-mcivor-s2xb", name="Eimear McIvor",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="eimear-sparks-63jc", name="Eimear Sparks",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="elizabeth-ferris-6ap9", name="Elizabeth Ferris",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="emily-brownlow-rn49", name="Emily Brownlow",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="emma-geary-fgqk", name="Emma Geary",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="emma-o-donnell-63jc", name="Emma O'Donnell",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="emma-power-rn49", name="Emma Power",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="emma-quigley-rn49", name="Emma Quigley",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="eoghan-cudmore-fgqk", name="Eoghan Cudmore",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="eoin-keller-afsz", name="Eoin Keller",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="fearghal-fitzgibbon-6ap9", name="Fearghal Fitzgibbon",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="ferdia-o-brien-t2xb", name="Ferdia O'Brien",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="finn-3gb6", name="Finn",
      ranking_rows=["iodai-ranking-2019-junior"], rows=[]),
    C(slug="finnegan-padraig-rn49", name="Finnegan Padraig",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="finn-murphy-eg3u", name="Finn Murphy",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="fintan-hughes-7acu", name="Fintan Hughes",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="fiona-byrne-ryan-rn49", name="Fiona Byrne-Ryan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="florence-fanning-63jc", name="Florence Fanning",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="gabrielle-brown-n7ek", name="Gabrielle Brown",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="gabrielle-browne-3k4y", name="Gabrielle Browne",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2007"], rows=[]),
    C(slug="gareth-henry-7acu", name="Gareth Henry",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="gareth-o-connor-eg3u", name="Gareth O'Connor",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="garreth-freeman-rn49", name="Garreth Freeman",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="garreth-henry-afsz", name="Garreth Henry",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="garry-scott-n7ek", name="Garry Scott",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="gary-mckenna-rn49", name="Gary McKenna",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="gary-scott-rn49", name="Gary Scott",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="gavin-donovan-rn49", name="Gavin Donovan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="gemma-collins-n7ek", name="Gemma Collins",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="george-hooker-rn49", name="George Hooker",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="georgina-corbett-afsz", name="Georgina Corbett",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="graham-corbett-t2xb", name="Graham Corbett",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="graham-daly-6ap9", name="Graham Daly",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="guy-aplin-63jc", name="Guy Aplin",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="holly-campbell-63jc", name="Holly Campbell",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="holly-jones-rn49", name="Holly Jones",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="iain-irvine-afsz", name="Iain Irvine",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="iarlaith-kennedy-eg3u", name="Iarlaith Kennedy",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="isabella-morehead-63jc", name="Isabella Morehead",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="isobel-forde-63jc", name="Isobel Forde",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jack-boland-63jc", name="Jack Boland",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jack-brien-63jc", name="Jack Brien",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jack-burke-fgqk", name="Jack Burke",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jack-costigan-eg3u", name="Jack Costigan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="jack-fitzpatrick-rn49", name="Jack Fitzpatrick",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="jamie-aplin-fgqk", name="Jamie Aplin",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jamie-carton-rn49", name="Jamie Carton",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="jane-butler-fgqk", name="Jane Butler",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jane-cudmore-n7ek", name="Jane Cudmore",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="jennifer-andreason-fgqk", name="Jennifer Andreason",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="jennifer-murphy-rn49", name="Jennifer Murphy",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="jessica-brien-t2xb", name="Jessica Brien",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="jill-roy-rn49", name="Jill Roy",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="jodie-jane-tingle-rn49", name="Jodie-Jane Tingle",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="john-drury-n7ek", name="John Drury",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="john-fisher-rn49", name="John Fisher",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="john-galvin-afsz", name="John Galvin",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="john-kingston-eg3u", name="John Kingston",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="john-willoughby-6ap9", name="John Willoughby",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="judy-costigan-rn49", name="Judy Costigan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="julie-donnellan-afsz", name="Julie Donnellan",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="julie-tingle-63jc", name="Julie Tingle",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="karl-mackey-t2xb", name="Karl Mackey",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="kate-fitzgerald-eg3u", name="Kate Fitzgerald",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="kate-magowan-s2xb", name="Kate Magowan",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="kate-o-leary-n7ek", name="Kate O'Leary",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="katie-gambier-ross-s2xb", name="Katie Gambier Ross",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="katie-mathews-n7ek", name="Katie Mathews",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="katie-matthews-3k4y", name="Katie Matthews",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2007"], rows=[]),
    C(slug="katie-tingle-rn49", name="Katie Tingle",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="katie-white-rn49", name="Katie White",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="keith-mcpartland-rn49", name="Keith McPartland",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="kelly-horgan-n7ek", name="Kelly Horgan",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="kevin-hickey-n7ek", name="Kevin Hickey",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="kieran-moriarty-6ap9", name="Kieran Moriarty",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="killian-o-keefe-eg3u", name="Killian O'Keefe",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="killian-o-keeffe-63jc", name="Killian O'Keeffe",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="kirsti-o-flynn-s2xb", name="Kirsti O'Flynn",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="leo-hickey-63jc", name="Leo Hickey",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="leonard-garland-6ap9", name="Leonard Garland",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="lewis-eickholt-afsz", name="Lewis Eickholt",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="louisa-schewe-rn49", name="Louisa Schewe",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="louise-schewe-6ap9", name="Louise Schewe",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="lucy-bolger-63jc", name="Lucy Bolger",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="lucy-bowan-n7ek", name="Lucy Bowan",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="luke-finnegan-rn49", name="Luke Finnegan",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="luke-hevers-afsz", name="Luke Hevers",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="maeve-counihan-eg3u", name="Maeve Counihan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="maeve-leonard-rn49", name="Maeve Leonard",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="maire-dineen-7acu", name="Maire Dineen",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="marc-geraghty-rn49", name="Marc Geraghty",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="mark-boylan-eg3u", name="Mark Boylan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="mark-condy-63jc", name="Mark Condy",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="mark-conmerford-n7ek", name="Mark Conmerford",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="mark-craig-eg3u", name="Mark Craig",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="mark-kelly-rn49", name="Mark Kelly",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="mark-lee-6ap9", name="Mark Lee",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="matthew-galvin-t2xb", name="Matthew Galvin",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="matthew-o-dowd-eg3u", name="Matthew O'Dowd",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="meadb-dickson-rn49", name="Meadb Dickson",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="meghan-darmody-6ap9", name="Meghan Darmody",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="michael-craig-s2xb", name="Michael Craig",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="michael-lynch-s2xb", name="Michael Lynch",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="muireann-guifoyle-6ap9", name="Muireann Guifoyle",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="muireann-guilfoyle-rn49", name="Muireann Guilfoyle",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="myles-kelly-n7ek", name="Myles Kelly",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="nessa-coady-rn49", name="Nessa Coady",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="niall-carberry-rn49", name="Niall Carberry",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="niall-collins-s2xb", name="Niall Collins",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="niamh-lane-rn49", name="Niamh Lane",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="niamh-o-connell-7acu", name="Niamh O'Connell",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="oisin-o-neill-n7ek", name="Oisin O'Neill",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="oliver-keenan-s2xb", name="Oliver Keenan",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="oliver-vivian-6ap9", name="Oliver Vivian",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="orlagh-thompsom-afsz", name="Orlagh Thompsom",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="oscar-morehead-afsz", name="Oscar Morehead",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="padraic-finnegan-afsz", name="Padraic Finnegan",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="padraig-finnegan-t2xb", name="Padraig Finnegan",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006"], rows=[]),
    C(slug="patrick-dix-eg3u", name="Patrick Dix",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="paul-martin-s2xb", name="Paul Martin",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="paul-o-connor-afsz", name="Paul O'Connor",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="peter-bermingham-eg3u", name="Peter Bermingham",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="peter-mannion-rn49", name="Peter Mannion",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="peter-mulvin-rn49", name="Peter Mulvin",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="philip-bendon-6ap9", name="Philip Bendon",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="philip-ryan-eg3u", name="Philip Ryan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="phoebe-tyrell-afsz", name="Phoebe Tyrell",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="rachel-guy-rn49", name="Rachel Guy",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="reuben-murray-whelan-6ap9", name="Reuben Murray Whelan",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="rian-breathnach-n7ek", name="Rian Breathnach",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="richard-harrington-fgqk", name="Richard Harrington",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="richard-murray-rn49", name="Richard Murray",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="richard-roberts-afsz", name="Richard Roberts",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="robbie-english-s2xb", name="Robbie English",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="robert-craig-rn49", name="Robert Craig",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="robert-murray-eg3u", name="Robert Murray",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="rob-lehane-rn49", name="Rob Lehane",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="robyn-lynch-n7ek", name="Robyn Lynch",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="roisin-lenegan-6ap9", name="Roisin Lenegan",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="roisin-leneghan-nsju", name="Roisin Leneghan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2006"], rows=[]),
    C(slug="rosie-moyles-6ap9", name="Rosie Moyles",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="ross-conlon-rn49", name="Ross Conlon",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="ross-darmody-rn49", name="Ross Darmody",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="ross-vaughan-eg3u", name="Ross Vaughan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="ruth-foy-rn49", name="Ruth Foy",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="ryan-gilmore-63jc", name="Ryan Gilmore",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="ryan-o-keefe-rn49", name="Ryan O'Keefe",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="ryan-scott-rn49", name="Ryan Scott",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="sallyann-tingle-eg3u", name="Sallyann Tingle",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="sam-bouma-rn49", name="Sam Bouma",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="sam-moloney-rn49", name="Sam Moloney",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="sarah-counihan-s2xb", name="Sarah Counihan",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="sarah-hogan-afsz", name="Sarah Hogan",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="sarah-kenny-s2xb", name="Sarah Kenny",
      ranking_rows=["iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="scott-flanigan-fgqk", name="Scott Flanigan",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="sean-anglin-afsz", name="Sean Anglin",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="sean-murphy-63jc", name="Sean Murphy",
      ranking_rows=["iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="sile-somers-afsz", name="Sile Somers",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="simone-mccarthy-afsz", name="Simone McCarthy",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="sinead-alcock-afsz", name="Sinead Alcock",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="suzanne-burke-rn49", name="Suzanne Burke",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="suzanne-roy-rn49", name="Suzanne Roy",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="tiernan-dickson-afsz", name="Tiernan Dickson",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="tiffany-brien-rn49", name="Tiffany Brien",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="timothy-moriarty-6ap9", name="Timothy Moriarty",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="timothy-o-laoire-eg3u", name="Timothy O'Laoire",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005"], rows=[]),
    C(slug="timothy-starr-afsz", name="Timothy Starr",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="tom-morehead-afsz", name="Tom Morehead",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="vicky-cudmore-afsz", name="Vicky Cudmore",
      ranking_rows=["iodai-ranking-2007"], rows=[]),
    C(slug="vikki-cudmore-n7ek", name="Vikki Cudmore",
      ranking_rows=["iodai-ranking-2006"], rows=[]),
    C(slug="wesley-brownlow-fgqk", name="Wesley Brownlow",
      ranking_rows=["iodai-ranking-2004", "iodai-ranking-2005", "iodai-ranking-2006", "iodai-ranking-2007"], rows=[]),
    C(slug="william-hooker-6ap9", name="William Hooker",
      ranking_rows=["iodai-ranking-2005"], rows=[]),
    C(slug="william-leech-rn49", name="William Leech",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="william-murray-rn49", name="William Murray",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
    C(slug="william-walesch-rn49", name="William Walesch",
      ranking_rows=["iodai-ranking-2004"], rows=[]),
]
